# Generated by Django 4.2.8 on 2023-12-21 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Verbit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verben', models.CharField(max_length=100, verbose_name='verb-en')),
                ('verbru', models.CharField(max_length=100, verbose_name='verb-en')),
                ('text', models.TextField(max_length=300, verbose_name='sample')),
            ],
        ),
    ]
